### ISSUE TITLE
version selector default should be latest

### ISSUE THREAD

**Issue by fbstj** [integer32llc/margo#19]
having checked out the [demo](https://integer32llc.github.io/margo-actions-demo/) site I noticed the versions dropdown was selecting v0.1.0 by default, and the items were sorted oldest at the top.

I would have expected the latest version to be displayed by default. either by reversing the order of the dropdown, or marking the latest version as `selected` (or otherwise html markup).

**Comment by shepmaster** [comment]
It should be as of 762bf73821a847710e97734acbe149a1382d76e4; I'm guessing we just haven't re-built the HTML for the demo since then.

**Comment by shepmaster** [comment]
Yep, bumped the version in the demo and it's selecting the latest version. Seem ok to you?

**Comment by fbstj** [comment]
yeah that certainly fixes this issue for me thanks :)
